---
name: Coverage
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Generate coverage
        run: make cov
      - name: Upload coverage
        uses: codecov/codecov-action@v2.0.1
        with:
          files: ./coverage.txt
          fail_ci_if_error: true
